services:
  db:
    image: postgres:16-alpine
    container_name: tx_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-transactions}
    ports:
      - "${DB_EXTERNAL_PORT:-5432}:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-transactions}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: tx_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-transactions}
      PORT: 8080
    ports:
      - "${PORT:-8080}:8080"
